### ISSUE TITLE
Bounding box of region of interest

### ISSUE THREAD

**Issue by Naxalov** [codeschooluz/chrome_dino#25]
# change of color bounding box 
![](https://github.com/codeschooluz/chrome_dino/raw/main/img/screen_bbox.png)

**Comment by RishiKumarRay** [comment]
I would like to solve this , can you guide me with this?

**Comment by Naxalov** [comment]
of course, actually, it is pretty simple. You should just change the color argument in this [part of the code](https://github.com/codeschooluz/chrome_dino/blob/d7d7ec278a18dfd45cf8bbb3ba4583641b2d93a8/perception/screen.py#L72)

**Comment by Naxalov** [comment]
> I would like to solve this , can you guide me with this?

of course, actually, it is pretty simple. You should just change the color argument in this part of the code

**Comment by RishiKumarRay** [comment]
ok i will do this, tell me which color should i change to

**Comment by Naxalov** [comment]
> ok i will do this , assign me , tell me which color should i change to
It doesn't matter. It is up to you

**Comment by RishiKumarRay** [comment]
Hey, After reading out, I have found out i need to change this argument only cv2.COLOR_BGR2GRAY is it correct, whereas earlier it was COLOR_BGR2HSV?

**Comment by Naxalov** [comment]
https://github.com/codeschooluz/chrome_dino/blob/d7d7ec278a18dfd45cf8bbb3ba4583641b2d93a8/perception/screen.py#L72

**Comment by RishiKumarRay** [comment]
fixed #27
